version: '3'
project_name: dns-frontend-services

services:
  web-app:
    container_name: dnsleads-fe
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3010:80
