version: '3'

services:
  web:
    build: .
    ports:
      - '3000:80'
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
