version: '3'
name: dnsleads-backend-services

services:
  mysql:
    container_name: mysqldb
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - dnsleads-vol:/var/lib/mysql
  web-api:
    container_name: dnsleads-be
    build: .
    restart: unless-stopped
    volumes:
      - static-files:/app/backend/static
    ports:
      - 5000:5000
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: 'mysql'
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
      ENV: ${ENV}
    env_file:
      - .env
volumes:
  dnsleads-vol:
    driver: local
  static-files:
    driver: local  
